# Day 5 of #15PetroNumpyDays

## zeroes, ones and identity matrixes
- Very useful in reservoir simulation

In [4]:
import numpy as np

In [5]:
#zeroes = place holder, useful in reservoir simulation, placeholder for values of properties of reservoir
zero = np.zeros((50,50))
zero

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [6]:
zero[1][2] = 30

In [7]:
zero

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0., 30., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [8]:
#ones = operations on reservoir grids 
p = np.ones((50,10))
p

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 

In [9]:
pi = 500
p*pi

array([[500., 500., 500., 500., 500., 500., 500., 500., 500., 500.],
       [500., 500., 500., 500., 500., 500., 500., 500., 500., 500.],
       [500., 500., 500., 500., 500., 500., 500., 500., 500., 500.],
       [500., 500., 500., 500., 500., 500., 500., 500., 500., 500.],
       [500., 500., 500., 500., 500., 500., 500., 500., 500., 500.],
       [500., 500., 500., 500., 500., 500., 500., 500., 500., 500.],
       [500., 500., 500., 500., 500., 500., 500., 500., 500., 500.],
       [500., 500., 500., 500., 500., 500., 500., 500., 500., 500.],
       [500., 500., 500., 500., 500., 500., 500., 500., 500., 500.],
       [500., 500., 500., 500., 500., 500., 500., 500., 500., 500.],
       [500., 500., 500., 500., 500., 500., 500., 500., 500., 500.],
       [500., 500., 500., 500., 500., 500., 500., 500., 500., 500.],
       [500., 500., 500., 500., 500., 500., 500., 500., 500., 500.],
       [500., 500., 500., 500., 500., 500., 500., 500., 500., 500.],
       [500., 500., 500., 500., 50

In [10]:
#eye: Creates an identity matrix
i = np.eye(4)
i

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
np.zeros((8,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])