# Numpy Functions

- Numpy contains a large number of various mathematical functions:
    - Trignometric
    - Arithmetic
    - Exponential, complex number handling etc.

In [1]:
import numpy as np

## Arithmetics Functions:

In [2]:
# Addition:
a = [1,2,3,44,5]
b = [4,5,6,7,8]
c= a+b
c

[1, 2, 3, 44, 5, 4, 5, 6, 7, 8]

In [3]:
c = []
for i,j in zip(a,b):
    c.append(i+j)
    
c

[5, 7, 9, 51, 13]

In [4]:
ara = np.array(a)
arb = np.array(b)
arc = ara +arb
arc

array([ 5,  7,  9, 51, 13])

In [5]:
a*b

TypeError: can't multiply sequence by non-int of type 'list'

In [6]:
ara*arb

array([  4,  10,  18, 308,  40])

In [7]:
a/b

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [8]:
ara/arb

array([0.25      , 0.4       , 0.5       , 6.28571429, 0.625     ])

In [9]:
a**b

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'list'

In [10]:
#Power
ara**arb

array([         1,         32,        729, 1450229760,     390625],
      dtype=int32)

In [11]:
ara 

array([ 1,  2,  3, 44,  5])

In [12]:
arb

array([4, 5, 6, 7, 8])

#### Operations between arrays of different shapes will result in error

In [13]:
arrd = np.array([1,23,4])

In [14]:
ara*arrd

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [15]:
a**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [16]:
ara**2

array([   1,    4,    9, 1936,   25], dtype=int32)

In [17]:
a*2

[1, 2, 3, 44, 5, 1, 2, 3, 44, 5]

In [18]:
ara*2

array([ 2,  4,  6, 88, 10])

In [19]:
#Quotient
ara//2

array([ 0,  1,  1, 22,  2], dtype=int32)

In [20]:
a//2

TypeError: unsupported operand type(s) for //: 'list' and 'int'

In [21]:
#Remainder
ara%2 

array([1, 0, 1, 0, 1], dtype=int32)

In [22]:
#absolute values
ar = np.array([-1,-5,-10,234,45,3])
np.abs(ar)

array([  1,   5,  10, 234,  45,   3])

In [23]:
np.sqrt(ara)

array([1.        , 1.41421356, 1.73205081, 6.63324958, 2.23606798])

In [24]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 6.63324958, 2.23606798])

In [25]:
a/0

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [26]:
ara/0

C:\Users\acer\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([inf, inf, inf, inf, inf])

In [27]:
np.inf

inf

In [28]:
np.nan

nan