# Day 15 of #15PetroNumpyDays

# Numpy Functions Part2

### Dot Product 

In [1]:
import numpy as np

In [2]:
ara = np.array([1,  2,  3, 44,  5])
arb = np.array([4, 5, 6, 7, 8])

In [3]:
ara

array([ 1,  2,  3, 44,  5])

In [4]:
arb

array([4, 5, 6, 7, 8])

In [5]:
ara.dot(arb)

380

In [6]:
#Transpose
are = np.array([[1,2,3,4],[5,6,7,8]])
are

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
are.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

### min,max,mean,std values


In [8]:
ard = np.array([1,2,4,6,7,8,9,-12,-45,-110,556,342])

In [9]:
ard.min()

-110

In [10]:
ard.max()

556

In [11]:
ard.argmin()

9

In [12]:
ard.argmax()

10

In [15]:
ard.sort()

In [16]:
ard

array([-110,  -45,  -12,    1,    2,    4,    6,    7,    8,    9,  342,
        556])

In [70]:
ard.mean()

64.0

In [71]:
ard.std()

180.61653671060503

### Rounding Function

In [72]:
ar = np.array([0.4,0.89,0.000035343,1.565677,3.5,88.97567463423,-1.54656778])

In [73]:
ar

array([ 4.00000000e-01,  8.90000000e-01,  3.53430000e-05,  1.56567700e+00,
        3.50000000e+00,  8.89756746e+01, -1.54656778e+00])

In [77]:
ar.round(4)

array([ 0.4   ,  0.89  ,  0.    ,  1.5657,  3.5   , 88.9757, -1.5466])

In [78]:
np.round(ar,4)

array([ 0.4   ,  0.89  ,  0.    ,  1.5657,  3.5   , 88.9757, -1.5466])

In [80]:
# Floor: Rounding to nearest lower integer
np.floor(ar)

array([ 0.,  0.,  0.,  1.,  3., 88., -2.])

In [81]:
# Ceil: ceil() function rounds off decimal to nearest upper integer.
np.ceil(ar)

array([ 1.,  1.,  1.,  2.,  4., 89., -1.])

## Trignometric Functions

In [82]:
ara

array([ 1,  2,  3, 44,  5])

In [83]:
np.sin(ara)

array([ 0.84147098,  0.90929743,  0.14112001,  0.01770193, -0.95892427])

In [86]:
np.sin(np.pi)

1.2246467991473532e-16

In [89]:
np.sin(0)

0.0

In [90]:
np.sin(np.pi/2)

1.0

In [91]:
np.cos(0)

1.0

In [92]:
np.cos(np.pi/2)

6.123233995736766e-17

In [17]:
arr = np.array([90, 180, 270, 360])

x = np.deg2rad(arr)

In [18]:
x

array([1.57079633, 3.14159265, 4.71238898, 6.28318531])

In [97]:
np.degrees(np.pi)

180.0

In [101]:
np.arcsin(1)

1.5707963267948966

In [102]:
np.rad2deg(np.arcsin(1))

90.0

In [120]:
np.rad2deg(np.arcsin([1,-1,0]))

array([ 90., -90.,   0.])

In [122]:
#hypot function that takes the base and perpendicular values and produces hypotenues
np.hypot(3,4)

5.0

## Logarthmic and Exponential functions

In [105]:
np.exp(1)

2.718281828459045

In [106]:
np.exp(2)

7.38905609893065

In [107]:
np.exp([1,2,4,6])

array([  2.71828183,   7.3890561 ,  54.59815003, 403.42879349])

In [111]:
#Natural log
np.log(1)

0.0

In [109]:
np.log(np.exp(1))

1.0

In [115]:
#Log base 10
np.log10(10)

1.0

In [116]:
np.log10(100)

2.0

In [119]:
#Log base 2
np.log2(2)

1.0

## Matrix Multiplication : use @
- a*b : a is of m X n and b is of n X j, then product is of m X j

In [123]:
ar = np.array([[2,3,4,5],[4,5,6,7]])

In [125]:
ar

array([[2, 3, 4, 5],
       [4, 5, 6, 7]])

In [124]:
ar.shape

(2, 4)

In [126]:
art = np.array([[1,2],[4,5],[6,7],[8,9]])
art

array([[1, 2],
       [4, 5],
       [6, 7],
       [8, 9]])

In [127]:
art.shape

(4, 2)

In [129]:
ar@art 

array([[ 78,  92],
       [116, 138]])