# Day 12 of #15PetroNumpyDays

# Random Number Generation 1

In [1]:
import numpy as np 

## Generating totally random numbers: 
- Doesn't follow any distributions

### Randint : Generating Random Integer
- provide the maximum number

In [2]:
np.random.randint(50,100)

69

In [3]:
a = np.random.randint(250,350,(4,3))

In [4]:
a

array([[256, 339, 315],
       [320, 319, 287],
       [307, 292, 288],
       [259, 314, 327]])

In [5]:
a = np.random.randint(250,350,(3,4,3))

In [6]:
a

array([[[282, 260, 348],
        [304, 295, 324],
        [290, 273, 314],
        [280, 292, 313]],

       [[256, 334, 289],
        [316, 330, 280],
        [258, 299, 253],
        [266, 313, 325]],

       [[325, 254, 297],
        [312, 325, 312],
        [337, 308, 311],
        [280, 304, 268]]])

### rand: Generating Random FLoat between 0 and 1
- provide size

In [7]:
np.random.rand()

0.5414177884340694

In [8]:
np.random.rand(5)

array([0.88920675, 0.47599235, 0.01606302, 0.50694702, 0.02045095])

In [9]:
np.random.rand(5,4)

array([[0.04668411, 0.5276426 , 0.15546227, 0.21617925],
       [0.02295024, 0.70006772, 0.30168797, 0.02475482],
       [0.16691251, 0.79535377, 0.48378792, 0.29412939],
       [0.39094127, 0.5584853 , 0.48702266, 0.59081801],
       [0.55601122, 0.27030386, 0.44516997, 0.77880107]])

In [10]:
np.random.rand(5,4,2)

array([[[0.12846978, 0.45411542],
        [0.93118591, 0.92026651],
        [0.94816721, 0.4838314 ],
        [0.98266435, 0.65996996]],

       [[0.99711212, 0.67790134],
        [0.19576955, 0.09826027],
        [0.87453202, 0.92221878],
        [0.7664368 , 0.63849025]],

       [[0.55540053, 0.30079785],
        [0.40914499, 0.39044007],
        [0.48366523, 0.58018903],
        [0.67436538, 0.57560239]],

       [[0.12801006, 0.3362617 ],
        [0.91548998, 0.4168268 ],
        [0.22971019, 0.37781503],
        [0.35878995, 0.25500486]],

       [[0.37593081, 0.61994554],
        [0.56946824, 0.81115177],
        [0.06071792, 0.5818838 ],
        [0.1829528 , 0.99039347]]])

In [11]:
inte = np.random.randint(200,size = (3,4))

In [12]:
fl = np.random.rand(3,4)

In [13]:
inte + fl

array([[105.07278653,  66.76112102,  83.57007618, 150.37231007],
       [181.12174968,  81.43485002, 137.31252787,  18.67509379],
       [166.74940839,  78.59494144,  72.95989415, 182.15318243]])

### Choice:
- generate a random value based on an array of values

In [14]:
np.random.choice([43,56,76,89])

56

In [15]:
np.random.choice([43,56,76,89],size = (3,5))

array([[89, 89, 76, 76, 56],
       [43, 76, 76, 89, 56],
       [56, 76, 76, 43, 43]])

### By using choice we can also specify probability for each value
- The sum of all probability numbers should be 1.

In [16]:
x = np.random.choice([3, 5, 7, 9], p=[1, 0, 0, 0], size=(5,6))

In [17]:
x

array([[3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3]])