# Day 2 of #15PetroNumpyDays

## numpy arrays: numpy object used for storing data:
Faster than lists(upto 50 times) and takes lesser space

In [1]:
# importing numpy
import numpy as np

In [2]:
#Creating Numpy array from a python list
a=[1,2,3,4,5]
arr = np.array(a)
arr

array([1, 2, 3, 4, 5])

In [3]:
type(arr)

numpy.ndarray

In [4]:
# Creating Numpy arrasy from tuples
import numpy as np
t = (1, 2, 3, 4, 5)

arr = np.array(t)

arr

array([1, 2, 3, 4, 5])

In [5]:
type(t)

tuple

In [6]:
type(arr)

numpy.ndarray

In [7]:
lis = list(arr)

In [8]:
lis

[1, 2, 3, 4, 5]

In [9]:
type(lis)

list

In [12]:
#Multi dimensional using lists of lists
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [13]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])