# Reshape

### Shape: The shape of an array is the number of elements in each dimension.

In [1]:
import numpy as np

In [2]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [3]:
arr.shape

(2, 4)

In [4]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
arr = np.array([[[1,2,3,4],[4,5,6,5]],[[3,4,5,8],[5,6,7,9]],[[23,34,56,78],[45,67,78,56]]])

In [6]:
arr

array([[[ 1,  2,  3,  4],
        [ 4,  5,  6,  5]],

       [[ 3,  4,  5,  8],
        [ 5,  6,  7,  9]],

       [[23, 34, 56, 78],
        [45, 67, 78, 56]]])

In [7]:
arr.shape

(3, 2, 4)

In [8]:
arr = np.array([1, 2, 3, 4], ndmin=5)


In [9]:
arr.shape

(1, 1, 1, 1, 4)

## Reshape: Changing the shape of array
- By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [10]:
a = np.array([1,2,3,4,5,6,7,8,9,67,12,45,24,678,89,56,454,23,56,76,89,89,65,45])

In [11]:
a.shape

(24,)

In [12]:
a.ndim

1

In [13]:
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  67,  12,  45,  24,
       678,  89,  56, 454,  23,  56,  76,  89,  89,  65,  45])

## Reshape from 1-D to 2-D

In [14]:
a2d = a.reshape(6,4)

In [15]:
a2d

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  67,  12,  45],
       [ 24, 678,  89,  56],
       [454,  23,  56,  76],
       [ 89,  89,  65,  45]])

In [16]:
a2d.shape

(6, 4)

In [17]:
a2d.ndim

2

## Reshape into 3-D
### 3 d array reshape((a,b,c)) = a is number of batches, b is number of rows, c is number of columns 

In [18]:
a3da = a.reshape(4,3,2)

In [19]:
a3da

array([[[  1,   2],
        [  3,   4],
        [  5,   6]],

       [[  7,   8],
        [  9,  67],
        [ 12,  45]],

       [[ 24, 678],
        [ 89,  56],
        [454,  23]],

       [[ 56,  76],
        [ 89,  89],
        [ 65,  45]]])

In [20]:
a3da.shape

(4, 3, 2)

In [21]:
a3da.ndim

3

In [22]:
a3db = a2d.reshape(4,3,2)

In [23]:
a3db

array([[[  1,   2],
        [  3,   4],
        [  5,   6]],

       [[  7,   8],
        [  9,  67],
        [ 12,  45]],

       [[ 24, 678],
        [ 89,  56],
        [454,  23]],

       [[ 56,  76],
        [ 89,  89],
        [ 65,  45]]])

## 4 D

In [24]:
a.reshape(2,2,3,2)

array([[[[  1,   2],
         [  3,   4],
         [  5,   6]],

        [[  7,   8],
         [  9,  67],
         [ 12,  45]]],


       [[[ 24, 678],
         [ 89,  56],
         [454,  23]],

        [[ 56,  76],
         [ 89,  89],
         [ 65,  45]]]])

## High dimensions

In [25]:
a.reshape(1,2,2,3,2)

array([[[[[  1,   2],
          [  3,   4],
          [  5,   6]],

         [[  7,   8],
          [  9,  67],
          [ 12,  45]]],


        [[[ 24, 678],
          [ 89,  56],
          [454,  23]],

         [[ 56,  76],
          [ 89,  89],
          [ 65,  45]]]]])

# Can we reshape into any shape?

In [26]:
a.reshape(7,3)

ValueError: cannot reshape array of size 24 into shape (7,3)

# Unknown dimension:
- You are allowed to have one "unknown" dimension.

- Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

- Pass -1 as the value, and NumPy will calculate this number for you.

In [27]:
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  67,  12,  45,  24,
       678,  89,  56, 454,  23,  56,  76,  89,  89,  65,  45])

In [28]:
a.shape

(24,)

In [29]:
a.reshape(1,24)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  67,  12,  45,  24,
        678,  89,  56, 454,  23,  56,  76,  89,  89,  65,  45]])

In [30]:
a.reshape(1,-1)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  67,  12,  45,  24,
        678,  89,  56, 454,  23,  56,  76,  89,  89,  65,  45]])

In [31]:
a.reshape(-1,1)

array([[  1],
       [  2],
       [  3],
       [  4],
       [  5],
       [  6],
       [  7],
       [  8],
       [  9],
       [ 67],
       [ 12],
       [ 45],
       [ 24],
       [678],
       [ 89],
       [ 56],
       [454],
       [ 23],
       [ 56],
       [ 76],
       [ 89],
       [ 89],
       [ 65],
       [ 45]])

In [32]:
a.reshape(3,-1)

array([[  1,   2,   3,   4,   5,   6,   7,   8],
       [  9,  67,  12,  45,  24, 678,  89,  56],
       [454,  23,  56,  76,  89,  89,  65,  45]])

In [33]:
a.reshape(5,-1)

ValueError: cannot reshape array of size 24 into shape (5,newaxis)

In [34]:
a.reshape(-1,2,3)

array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [ 67,  12,  45]],

       [[ 24, 678,  89],
        [ 56, 454,  23]],

       [[ 56,  76,  89],
        [ 89,  65,  45]]])

In [35]:
a.reshape(2,-1,4)

array([[[  1,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  67,  12,  45]],

       [[ 24, 678,  89,  56],
        [454,  23,  56,  76],
        [ 89,  89,  65,  45]]])

In [36]:
a.reshape(2,-1,4)

array([[[  1,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  67,  12,  45]],

       [[ 24, 678,  89,  56],
        [454,  23,  56,  76],
        [ 89,  89,  65,  45]]])

In [37]:
a.reshape(-1,2,2,2) # 3 3d matrices of 2 2*2 2d matrices

array([[[[  1,   2],
         [  3,   4]],

        [[  5,   6],
         [  7,   8]]],


       [[[  9,  67],
         [ 12,  45]],

        [[ 24, 678],
         [ 89,  56]]],


       [[[454,  23],
         [ 56,  76]],

        [[ 89,  89],
         [ 65,  45]]]])