# Day 3 of #15PetroNumpyDays

# Arrays Dimension and Shape

In [1]:
import numpy as np

In [4]:
arr = np.array(45)

In [5]:
#Checking Dimension of array using ndim attribute
arr.ndim

0

In [6]:
arr

array(45)

### 1-D array : Array having 0-D arrays as its elements
- Most common and basic arrays
- Similar to basic lists

In [7]:
arr = np.array((42,34,45))

In [8]:
arr.ndim

1

In [9]:
arr

array([42, 34, 45])

### 2-D array: Array having 1-D arrays as its elements.
- Represents matrix or 2md order tensor

In [10]:
arr = np.array([[1,2,3],[4,5,6]])

In [11]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
arr.ndim

2

In [13]:
mat  = np.mat(np.array([[1,2,3],[4,5,6]]))

In [14]:
mat

matrix([[1, 2, 3],
        [4, 5, 6]])

In [15]:
type(mat)

numpy.matrix

In [16]:
mat.ndim

2

### 3- D array : 2-D arrays behave as element
- Represents 3rd order tensor

In [17]:
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[3,4,5]]])

In [18]:
arr.ndim

3

In [19]:
arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [3, 4, 5]]])

### Higher Dimesnional Arrays
- An array can have any number of dimensions
- ndmin argument

In [20]:
arr = np.array([1,2,3], ndmin = 5)

In [21]:
arr

array([[[[[1, 2, 3]]]]])

In [22]:
arr.ndim

5

### Shape: Checking shape

In [23]:
arr = np.array([[1,2,3],[4,5,6]])

In [24]:
arr.shape

(2, 3)

In [25]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[3,4,5]]])

In [27]:
arr.shape

(2, 2, 3)

In [28]:
arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [3, 4, 5]]])